// 
// Do not edit this file, it is automatically generated!
// To generate this file, "make design.h" in the rtl directory.
// 
#ifndef DESIGN_H
#define DESIGN_H

#define	XULA25
#define	INCLUDE_ZIPCPU
#ifndef	INCLUDE_ZIPCPU
#define	NO_ZIP_WBU_DELAY
#endif
#ifdef	VERILATOR
#define	NO_ZIP_WBU_DELAY
#endif
#define	IMPLEMENT_ONCHIP_RAM
#ifndef	VERILATOR
#ifndef	XULA25
#endif
#endif
#define	FLASH_ACCESS
#define SDCARD_ACCESS
#ifndef	FLASH_SCOPE
#endif
#ifdef	XULA25
#ifdef	FANCY_ICAP_ACCESS
#else
#ifdef	SDCARD_ACCESS
#endif
#endif
#endif
#ifdef	INCLUDE_ZIPCPU
#ifdef	VERILATOR
#define	ZIP_SCOPE
#else // !VERILATOR
#ifdef	XULA25
#endif // XULA25
#endif // VERILATOR
#endif // INCLUDE_ZIPCPU
#ifdef	INCLUDE_ZIPCPU
#else
#endif
#ifdef	INCLUDE_ZIPCPU
#ifdef	ZIP_SCOPE
#endif
#ifdef	XULA25
#ifdef	ZIP_SCOPE
#endif
#else
#ifdef	ZIP_SCOPE
#endif
#endif
#ifdef	NO_ZIP_WBU_DELAY
#else
#endif
#else // if no ZIP_CPU
#endif
#define	SPEEDY_IO
#ifndef	SPEEDY_IO
#ifdef	SDCARD_ACCESS
#else
#endif
#else
#endif
#ifdef	XULA25
#else
#endif
#ifdef	XULA25
#ifdef	FMHACK
#else
#endif
#else	// XULA25
#endif
#ifdef	FMHACK
#else
#endif
#ifdef	FLASH_ACCESS
#else
#endif
#ifdef	SDCARD_ACCESS
#else
#endif	// SDCARD_ACCESS
#ifdef	FLASH_ACCESS
#ifdef	SDCARD_ACCESS
#else
#endif // SDCARD_ACCESS && FLASH_ACCESS
#else // FLASH_ACCESS
#ifdef	SDCARD_ACCESS
#else
#endif // SDCARD_ACCESS, w/o FLASH_ACCESS
#endif // !FLASH_ACCESS
#ifdef	FANCY_ICAP_ACCESS
#else
#endif
#ifdef	IMPLEMENT_ONCHIP_RAM
#else
#endif
#ifndef	BYPASS_SDRAM_ACCESS
#else
#endif
#ifndef	FLASH_ACCESS
#ifdef	FLASH_SCOPE
#undef	FLASH_SCOPE // FLASH_SCOPE only makes sense if you have flash access
#endif
#endif
#ifdef	FLASH_SCOPE
#else
#ifdef	WBUS_SCOPE
#else
#endif
#endif
#ifdef	CFG_SCOPE
#else
#ifdef	SDCARD_SCOPE
#else
#endif
#endif
#ifdef	SDRAM_SCOPE
#else
#ifdef	UART_SCOPE
#else
#endif
#endif
#ifdef	ZIP_SCOPE
#else
#endif
#ifndef	XULA25
#endif

#endif // DESIGN_H
